export type BadgeConfig = {
  logo?: string;
  color: string;
};

const badgeMap: Record<string, BadgeConfig> = {
  "Node.js": { logo: "nodedotjs", color: "339933" },
  Node: { logo: "nodedotjs", color: "339933" },
  NestJS: { logo: "nestjs", color: "E0234E" },
  Express: { logo: "express", color: "000000" },
  "Express.js": { logo: "express", color: "000000" },
  TypeScript: { logo: "typescript", color: "3178C6" },
  Typescript: { logo: "typescript", color: "3178C6" },
  JavaScript: { logo: "javascript", color: "F7DF1E" },
  Javascript: { logo: "javascript", color: "F7DF1E" },
  React: { logo: "react", color: "61DAFB" },
  "Redux.js": { logo: "redux", color: "764ABC" },
  Tailwind: { logo: "tailwindcss", color: "06B6D4" },
  CSS: { logo: "css3", color: "1572B6" },
  HTML: { logo: "html5", color: "E34F26" },
  HTML5: { logo: "html5", color: "E34F26" },
  Firebase: { logo: "firebase", color: "FFCA28" },
  Firestore: { logo: "firebase", color: "FFCA28" },
  "Firebase Authentication": { logo: "firebase", color: "FFCA28" },
  "Google Cloud": { logo: "googlecloud", color: "4285F4" },
  GCP: { logo: "googlecloud", color: "4285F4" },
  Prisma: { logo: "prisma", color: "2D3748" },
  TypeORM: { color: "FE0803" },
  MySQL: { logo: "mysql", color: "4479A1" },
  MongoDB: { logo: "mongodb", color: "47A248" },
  PostgreSQL: { logo: "postgresql", color: "4169E1" },
  Postgres: { logo: "postgresql", color: "4169E1" },
  Postman: { logo: "postman", color: "FF6C37" },
  Swagger: { logo: "swagger", color: "85EA2D" },
  S3: { logo: "amazons3", color: "569A31" },
  AWS: { logo: "amazonwebservices", color: "232F3E" },
  Docker: { logo: "docker", color: "2496ED" },
  Git: { logo: "git", color: "F05032" },
  GitHub: { logo: "github", color: "181717" },
  Python: { logo: "python", color: "3776AB" },
  Jest: { logo: "jest", color: "C21325" },
  Linux: { logo: "linux", color: "FCC624" },
  Bootstrap: { logo: "bootstrap", color: "7952B3" },
  "Sequelize.js": { logo: "sequelize", color: "52B0E7" },
  Sequelize: { logo: "sequelize", color: "52B0E7" },
  ".NET Framework": { logo: "dotnet", color: "512BD4" },
  ".NET": { logo: "dotnet", color: "512BD4" },
  SQL: { color: "4479A1" },
  NoSQL: { color: "47A248" },
  JSON: { logo: "json", color: "000000" },
  Kanban: { color: "0052CC" },
  Scrum: { color: "6DB33F" },
  Frontend: { color: "61DAFB" },
  Backend: { color: "339933" },
  "Banco de dados": { color: "4169E1" },
  "Bancos de dados relacionais": { color: "4169E1" },
  "API REST": { color: "009688" },
  "Web design": { color: "FF61F6" },
  "Web Design Responsivo": { color: "FF61F6" },
  "Automação de testes": { color: "C21325" },
  "Teste de integração": { color: "C21325" },
  "HTML semântico": { logo: "html5", color: "E34F26" },
  "Modelagem de Dados": { color: "4169E1" },
  "Técnicas de Desenvolvimento de Algoritmos": { color: "007ACC" },
  "Conjuntos Numéricos": { color: "3776AB" },
  "Atendimento ao cliente": { color: "FF6B6B" },
  Organização: { color: "4ECDC4" },
  "Trabalho em equipe": { color: "45B7D1" },
  Administração: { color: "6C5CE7" },
  Finanças: { color: "00B894" },
  Angular: { logo: "angular", color: "DD0031" },
  "Next.js": { logo: "nextdotjs", color: "000000" },
  Shadcn: { color: "000000" },
  Zustand: { color: "433E38" },
  Zod: { logo: "zod", color: "3E67B1" },
  Bun: { logo: "bun", color: "000000" },
  Context: { logo: "react", color: "61DAFB" },
  Java: { logo: "openjdk", color: "ED8B00" },
  "Springboot 3": { logo: "springboot", color: "6DB33F" },
  Mermaid: { color: "FF3670" },
  "Json Web Token": { logo: "jsonwebtokens", color: "000000" },
  JWT: { logo: "jsonwebtokens", color: "000000" },
  Joi: { color: "0080FF" },
  Helmet: { color: "000000" },
  bcrypt: { color: "003A70" },
  Sqlite: { logo: "sqlite", color: "003B57" },
  Vercel: { logo: "vercel", color: "000000" },
  "Entity Framework": { logo: "dotnet", color: "512BD4" },
  "Sql Server": { logo: "microsoftsqlserver", color: "CC2927" },
  npm: { logo: "npm", color: "CB3837" },
  fs: { logo: "nodedotjs", color: "339933" },
  MariaDB: { logo: "mariadb", color: "003545" },
  WebSocket: { color: "010101" },
  SSE: { color: "FF6B6B" },
  Stripe: { logo: "stripe", color: "008CDD" },
  "Pagar.me": { color: "00A868" },
  Asaas: { color: "1A1A2E" },
  SendGrid: { color: "1A82E2" },
  Brevo: { color: "0B996E" },
  "Cron Jobs": { color: "4A5568" },
  "Cloud Storage": { logo: "googlecloud", color: "4285F4" },
  "Cloud Functions": { logo: "googlecloud", color: "4285F4" },
  EC2: { logo: "amazonec2", color: "FF9900" },
  RDS: { logo: "amazonrds", color: "527FFF" },
  SOLID: { color: "007ACC" },
  "Clean Code": { color: "2ECC71" },
  "Arquitetura de Software": { color: "9B59B6" },
};

const defaultBadge: BadgeConfig = { color: "555555" };

export function getBadgeConfig(name: string): BadgeConfig {
  return badgeMap[name] || defaultBadge;
}

export function buildBadgeUrl(name: string): string {
  const config = badgeMap[name] || defaultBadge;
  const baseUrl = "https://img.shields.io/badge";
  const encodedName = encodeURIComponent(name.replace(/-/g, "--"));
  const logoParam = config.logo ? `&logo=${config.logo}&logoColor=white` : "";
  return `${baseUrl}/${encodedName}-${config.color}?style=flat${logoParam}`;
}
